regionImagePrefixes = {
  # cave dw
  327691: [
    'dh_a01_floor01_'],  #Donwhang Stone Cave [1F]
   
  
  327692:[
 'dh_a01_floor02_', # Donwhang Stone Cave [2F]
  ],
  327693: ['dh_a01_floor03_', # Donwhang Stone Cave [3F]
   

  ],
  327694: [
     'dh_a01_floor04_', # Donwhang Stone Cave [4F]
  ],
  #cave jg
  32775: ['qt_a01_floor01_'], #Underground Level 1 of Tomb of Qui-Shin [B1]
  32774: ['qt_a01_floor02_'], # Underground Level 2 of Tomb of Qui-Shin [B2]
  32773: ['qt_a01_floor03_'], # Underground Level 3 of Tomb of Qui-Shin [B3]
  32772: ['qt_a01_floor04_'], # Underground Level 4 of Tomb of Qui-Shin [B4]
  32771: ['qt_a01_floor05_'], #Underground Level 5 of Tomb of Qui-Shin [B5]
  32770: ['qt_a01_floor06_'], # Underground Level 5 of Tomb of Qui-Shin [B5]
  # job temple 
  32784: ['rn_sd_egypt1_01_'], #Temple
  32783: ['rn_sd_egypt1_02_'], # Sanctum of Seth
  32782: ['rn_sd_egypt1_01_'], #Sanctum of Haroeris
  32781: ['rn_sd_egypt1_01_'], # Sanctum of Isis
  32780: ['rn_sd_egypt1_01_'], # Sanctum of Anubis
  32779: ['rn_sd_egypt1_01_'], #Sanctum of Blue Eye
  #cave generated by fortress war
  32785: ['fort_dungeon01_'], # Cave of Meditation [1F]
  # mountain flame
  32786: ['flame_dungeon01_'], # Flame Mountain
  # jupiter rooms
  32787: ['rn_jupiter_02_'], #The Earth\'s Room
  32788: ['rn_jupiter_03_'], # Yuno\'s Room
  32789: ['rn_jupiter_04_'], # Jupiter\'s Room
  32790: ['rn_jupiter_01_'], #Zealots Hideout
  32793: ['RN_ARABIA_FIELD_02_BOSS_'], # Kalia\'s Hideout
}
